export const content = {
	pt: {
		nameTitle: 'Por que Vértice?',
		nameMeaning: 'Vértice representa o ponto de encontro entre negócios, dados e tecnologia. Nosso nome traduz a conexão dessas três frentes para criar novas perspectivas, dar clareza às decisões e encontrar a direção do próximo passo da sua empresa.',
		nav: ['Expertise', 'Como trabalhamos', 'Sobre nós', 'Nosso time'],
		contact: 'Vamos conversar',
		eyebrow: 'ESTRATÉGIA + DADOS + TECNOLOGIA',
		hero: ['Menos complexidade.', 'Mais clareza.', 'Novas possibilidades.'],
		intro: 'Transformamos dados em direção. Conectamos inteligência financeira, processos e tecnologia para levar seu negócio ao próximo nível.',
		explore: 'Explore nossas soluções',
		scroll: 'O próximo passo começa aqui',
		strip: ['BUSINESS INTELLIGENCE', 'INTELIGÊNCIA ARTIFICIAL', 'AUTOMAÇÃO', 'APLICAÇÕES SOB MEDIDA'],
		expertise: 'O QUE FAZEMOS',
		title: 'Seu próximo salto\ncomeça com clareza.',
		subtitle: 'Do primeiro diagnóstico à solução em operação. Tecnologia que resolve o que realmente importa para o seu negócio.',
		services: [
			['Business Intelligence', 'Enxergue além dos números.', 'Dashboards executivos, indicadores e visualização de dados financeiros para decisões mais seguras.', 'Dashboards · KPIs · Analytics'],
			['Dados & Queries', 'A resposta certa começa na base.', 'Organizamos fontes, otimizamos consultas SQL e conectamos dados para criar uma visão confiável do negócio.', 'SQL · Integração · Qualidade'],
			['Processos & Automação', 'Menos tarefas. Mais possibilidades.', 'Mapeamos gargalos e automatizamos rotinas para que seu time possa focar em trabalho de maior valor.', 'Workflows · APIs · Eficiência'],
			['IA, Chatbots & Agentes', 'Inteligência com propósito.', 'Avaliamos onde a IA faz sentido e criamos assistentes e agentes com supervisão e limites definidos.', 'IA generativa · Assistentes · Agentes'],
			['Aplicações sob medida', 'Seu desafio não vem pronto. A solução também não.', 'Desenvolvemos portais, sistemas e aplicativos conectados à realidade e aos processos da sua empresa.', 'Web · Apps · Sistemas internos'],
		],
		learn: 'Explorar solução',
		view: 'VISÃO FINANCEIRA',
		demo: 'DADOS ILUSTRATIVOS',
		financial: 'Seus números.\nUma nova perspectiva.',
		finDesc: 'Conecte receita, despesas e resultados em uma visão que toda a liderança entende. Explore um exemplo de como podemos transformar seus dados.',
		periods: ['1º semestre', '2º semestre'],
		revenue: 'Receita total',
		margin: 'Margem operacional',
		result: 'Resultado',
		chart: 'Receita e despesas por mês',
		legends: ['Receita', 'Despesas'],
		months: [['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun'], ['Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']],
		method: 'COMO TRABALHAMOS',
		methodTitle: 'Próximos do seu negócio.\nDo início ao próximo passo.',
		steps: [['Entender', 'Ouvimos seu time, mapeamos o cenário e identificamos as oportunidades.'], ['Desenhar', 'Definimos prioridades, entregáveis e critérios de sucesso com você.'], ['Construir', 'Desenvolvemos e validamos a solução em ciclos curtos e colaborativos.'], ['Evoluir', 'Acompanhamos a adoção, transferimos conhecimento e melhoramos juntos.']],
		about: 'SOMOS A VÉRTICE',
		aboutTitle: 'O ponto de encontro entre\nnegócios e tecnologia.',
		aboutDesc: 'A Vértice nasce para aproximar empresas do potencial dos seus dados. Combinamos visão de negócio e desenvolvimento de soluções para tornar processos mais simples e decisões mais claras.',
		principles: ['Entender antes de construir', 'Soluções para o seu contexto', 'Conhecimento que fica com seu time'],
		teamLabel: 'PESSOAS POR TRÁS DAS SOLUÇÕES',
		teamTitle: 'Tecnologia feita por pessoas.\nPara pessoas.',
		teamNote: 'Perfis e fotografias ilustrativos — substitua pelas pessoas da sua equipe antes da publicação.',
		ctaLabel: 'VAMOS CONSTRUIR O PRÓXIMO PASSO?',
		cta: 'Seu negócio tem um desafio.\nVamos encontrar a direção.',
		ctaText: 'Conte o que você quer transformar. O primeiro passo é uma boa conversa.',
		ctaButton: 'Conte seu desafio',
		footer: 'Clareza para decidir. Tecnologia para evoluir.',
		rights: 'Todos os direitos reservados.',
		back: 'Voltar ao topo',
		light: 'Ativar modo claro',
		dark: 'Ativar modo escuro',
		menu: 'Abrir navegação',
		close: 'Fechar',
		language: 'Idioma',
		skip: 'Ir para o conteúdo',
		formTitle: 'Vamos entender seu desafio.',
		formDesc: 'Prepare um resumo do seu projeto para iniciar uma conversa com a Vértice.',
		name: 'Seu nome',
		company: 'Empresa',
		email: 'E-mail profissional',
		challenge: 'O que você quer transformar?',
		submit: 'Preparar contato',
		download: 'Baixar resumo do projeto',
		formNote: 'O contato da equipe ainda não foi configurado. Você pode baixar seu resumo; nenhum dado será enviado.',
		ready: 'Resumo pronto. Abra seu aplicativo de e-mail ou baixe uma cópia.',
		send: 'Abrir e-mail',
		error: 'Não foi possível concluir. Tente novamente.',
		assistant: 'Assistente Vértice',
		assistantDesc: 'Explore nossas soluções',
		aiDemo: 'Guia de serviços · respostas locais, sem IA conectada',
		aiLive: 'Assistente com IA · evite compartilhar dados sensíveis',
		aiHello: 'Olá! Qual área você quer transformar? Escolha um tema ou descreva seu desafio.',
		aiPlaceholder: 'Conte seu desafio…',
		aiSend: 'Enviar mensagem',
		aiBusy: 'Preparando resposta…',
		aiFail: 'O assistente está indisponível. Tente novamente ou fale com a equipe.',
		aiDefault: 'Podemos ajudar com BI, dados, automação, IA e aplicações. Qual dessas áreas se aproxima do seu desafio?',
		aiTopics: ['Visualizar dados financeiros', 'Automatizar processos', 'Explorar IA'],
		aiAnswers: ['Podemos organizar suas fontes e criar dashboards de receita, despesas, margem e indicadores. O primeiro passo é entender quais decisões seu time precisa tomar.', 'Começamos mapeando tarefas repetitivas, sistemas envolvidos e pontos de aprovação. Depois propomos integrações e automações adequadas ao processo.', 'Avaliamos o caso de uso, os dados disponíveis e os riscos antes de propor chatbots ou agentes. Supervisão humana e critérios de avaliação fazem parte da solução.'],
		solutionCTA: 'Conversar sobre esta solução',
	},
	en: {
		nameTitle: 'Why Vértice?',
		nameMeaning: 'Vértice means vertex: a meeting point between business, data and technology. Our name reflects how we connect these three disciplines to create new perspectives, bring clarity to decisions and help your company find its next direction.',
		nav: ['Expertise', 'Our approach', 'About us', 'Our team'],
		contact: 'Let’s talk',
		eyebrow: 'STRATEGY + DATA + TECHNOLOGY',
		hero: ['Less complexity.', 'More clarity.', 'New possibilities.'],
		intro: 'We turn data into direction. Connecting financial intelligence, processes and technology to take your business forward.',
		explore: 'Explore our solutions',
		scroll: 'Your next step starts here',
		strip: ['BUSINESS INTELLIGENCE', 'ARTIFICIAL INTELLIGENCE', 'AUTOMATION', 'CUSTOM APPLICATIONS'],
		expertise: 'WHAT WE DO',
		title: 'Your next leap\nstarts with clarity.',
		subtitle: 'From the first discovery to a working solution. Technology that solves what truly matters to your business.',
		services: [['Business Intelligence', 'See beyond the numbers.', 'Executive dashboards, metrics and financial data visualization for more confident decisions.', 'Dashboards · KPIs · Analytics'], ['Data & Queries', 'The right answer starts at the source.', 'We organize sources, optimize SQL queries and connect data for a trustworthy view of your business.', 'SQL · Integration · Quality'], ['Processes & Automation', 'Fewer tasks. More possibilities.', 'We map bottlenecks and automate routines so your team can focus on higher-value work.', 'Workflows · APIs · Efficiency'], ['AI, Chatbots & Agents', 'Intelligence with purpose.', 'We assess where AI makes sense and create assistants and agents with clear boundaries and oversight.', 'Generative AI · Assistants · Agents'], ['Custom Applications', 'Your challenge is unique. Your solution should be too.', 'We build portals, systems and applications connected to your company’s reality and processes.', 'Web · Apps · Internal systems']],
		learn: 'Explore solution',
		view: 'FINANCIAL PERSPECTIVE',
		demo: 'ILLUSTRATIVE DATA',
		financial: 'Your numbers.\nA new perspective.',
		finDesc: 'Connect revenue, expenses and results in a view every leader understands. Explore an example of how we can transform your data.',
		periods: ['First half', 'Second half'],
		revenue: 'Total revenue',
		margin: 'Operating margin',
		result: 'Profit',
		chart: 'Monthly revenue and expenses',
		legends: ['Revenue', 'Expenses'],
		months: [['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']],
		method: 'OUR APPROACH',
		methodTitle: 'Close to your business.\nFrom day one to what’s next.',
		steps: [['Discover', 'We listen to your team, map the landscape and identify opportunities.'], ['Design', 'Together we define priorities, deliverables and success criteria.'], ['Build', 'We develop and validate the solution in short, collaborative cycles.'], ['Evolve', 'We support adoption, share knowledge and improve together.']],
		about: 'WE ARE VÉRTICE',
		aboutTitle: 'Where business\nmeets technology.',
		aboutDesc: 'Vértice brings companies closer to the potential of their data. We combine business understanding and solution development to simplify processes and make decisions clearer.',
		principles: ['Understand before building', 'Solutions for your context', 'Knowledge that stays with your team'],
		teamLabel: 'THE PEOPLE BEHIND THE SOLUTIONS',
		teamTitle: 'Technology made by people.\nFor people.',
		teamNote: 'Illustrative profiles and photographs — replace with your real team before publishing.',
		ctaLabel: 'READY TO BUILD WHAT’S NEXT?',
		cta: 'Your business has a challenge.\nLet’s find the direction.',
		ctaText: 'Tell us what you want to transform. The first step is a good conversation.',
		ctaButton: 'Tell us your challenge',
		footer: 'Clarity to decide. Technology to evolve.',
		rights: 'All rights reserved.',
		back: 'Back to top',
		light: 'Enable light mode',
		dark: 'Enable dark mode',
		menu: 'Open navigation',
		close: 'Close',
		language: 'Language',
		skip: 'Skip to content',
		formTitle: 'Let’s understand your challenge.',
		formDesc: 'Prepare a project brief to start a conversation with Vértice.',
		name: 'Your name',
		company: 'Company',
		email: 'Work email',
		challenge: 'What would you like to transform?',
		submit: 'Prepare contact',
		download: 'Download project brief',
		formNote: 'The team’s contact address is not configured yet. You can download your brief; no data will be sent.',
		ready: 'Your brief is ready. Open your email app or download a copy.',
		send: 'Open email',
		error: 'Unable to complete. Please try again.',
		assistant: 'Vértice Assistant',
		assistantDesc: 'Explore our solutions',
		aiDemo: 'Service guide · local answers, no AI connected',
		aiLive: 'AI assistant · avoid sharing sensitive data',
		aiHello: 'Hi! What would you like to transform? Choose a topic or describe your challenge.',
		aiPlaceholder: 'Tell us your challenge…',
		aiSend: 'Send message',
		aiBusy: 'Preparing a reply…',
		aiFail: 'The assistant is unavailable. Try again or contact the team.',
		aiDefault: 'We can help with BI, data, automation, AI and applications. Which area best describes your challenge?',
		aiTopics: ['Visualize financial data', 'Automate processes', 'Explore AI'],
		aiAnswers: ['We can organize your sources and build dashboards for revenue, expenses, margins and metrics. We start by understanding the decisions your team needs to make.', 'We begin by mapping repetitive tasks, systems and approval points. Then we propose suitable integrations and automations.', 'We assess your use case, available data and risks before proposing chatbots or agents. Human oversight and evaluation criteria are part of the solution.'],
		solutionCTA: 'Discuss this solution',
	},
	es: {
		nameTitle: '¿Por qué Vértice?',
		nameMeaning: 'Vértice representa el punto de encuentro entre negocios, datos y tecnología. Nuestro nombre refleja la conexión de estas tres áreas para crear nuevas perspectivas, aportar claridad a las decisiones y encontrar la dirección del próximo paso de su empresa.',
		nav: ['Especialidades', 'Cómo trabajamos', 'Nosotros', 'Equipo'],
		contact: 'Conversemos',
		eyebrow: 'ESTRATEGIA + DATOS + TECNOLOGÍA',
		hero: ['Menos complejidad.', 'Más claridad.', 'Nuevas posibilidades.'],
		intro: 'Transformamos datos en dirección. Conectamos inteligencia financiera, procesos y tecnología para impulsar su negocio.',
		explore: 'Explore nuestras soluciones',
		scroll: 'El próximo paso empieza aquí',
		strip: ['BUSINESS INTELLIGENCE', 'INTELIGENCIA ARTIFICIAL', 'AUTOMATIZACIÓN', 'APLICACIONES A MEDIDA'],
		expertise: 'QUÉ HACEMOS',
		title: 'Su próximo salto\nempieza con claridad.',
		subtitle: 'Desde el diagnóstico hasta la solución en operación. Tecnología que resuelve lo que realmente importa para su negocio.',
		services: [['Business Intelligence', 'Vea más allá de los números.', 'Dashboards ejecutivos, indicadores y visualización de datos financieros para decisiones más seguras.', 'Dashboards · KPIs · Analytics'], ['Datos & Consultas', 'La respuesta empieza en la base.', 'Organizamos fuentes, optimizamos consultas SQL y conectamos datos para una visión confiable del negocio.', 'SQL · Integración · Calidad'], ['Procesos & Automatización', 'Menos tareas. Más posibilidades.', 'Identificamos obstáculos y automatizamos rutinas para que su equipo se enfoque en trabajo de mayor valor.', 'Workflows · APIs · Eficiencia'], ['IA, Chatbots & Agentes', 'Inteligencia con propósito.', 'Evaluamos dónde la IA tiene sentido y creamos asistentes y agentes con supervisión y límites claros.', 'IA generativa · Asistentes · Agentes'], ['Aplicaciones a medida', 'Su desafío es único. Su solución también.', 'Desarrollamos portales, sistemas y aplicaciones conectados a la realidad de su empresa.', 'Web · Apps · Sistemas internos']],
		learn: 'Explorar solución',
		view: 'VISIÓN FINANCIERA',
		demo: 'DATOS ILUSTRATIVOS',
		financial: 'Sus números.\nUna nueva perspectiva.',
		finDesc: 'Conecte ingresos, gastos y resultados en una visión que todo el liderazgo entiende. Explore cómo podemos transformar sus datos.',
		periods: ['Primer semestre', 'Segundo semestre'],
		revenue: 'Ingresos totales',
		margin: 'Margen operativo',
		result: 'Resultado',
		chart: 'Ingresos y gastos por mes',
		legends: ['Ingresos', 'Gastos'],
		months: [['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun'], ['Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']],
		method: 'CÓMO TRABAJAMOS',
		methodTitle: 'Cerca de su negocio.\nDel inicio al próximo paso.',
		steps: [['Entender', 'Escuchamos a su equipo, analizamos el escenario e identificamos oportunidades.'], ['Diseñar', 'Definimos prioridades, entregables y criterios de éxito juntos.'], ['Construir', 'Desarrollamos y validamos en ciclos cortos y colaborativos.'], ['Evolucionar', 'Apoyamos la adopción, transferimos conocimiento y mejoramos juntos.']],
		about: 'SOMOS VÉRTICE',
		aboutTitle: 'El punto de encuentro entre\nnegocios y tecnología.',
		aboutDesc: 'Vértice acerca a las empresas al potencial de sus datos. Combinamos visión de negocio y desarrollo de soluciones para simplificar procesos y aclarar decisiones.',
		principles: ['Entender antes de construir', 'Soluciones para su contexto', 'Conocimiento que se queda con su equipo'],
		teamLabel: 'PERSONAS DETRÁS DE LAS SOLUCIONES',
		teamTitle: 'Tecnología hecha por personas.\nPara personas.',
		teamNote: 'Perfiles y fotografías ilustrativos — sustitúyalos por su equipo antes de publicar.',
		ctaLabel: '¿CONSTRUIMOS EL PRÓXIMO PASO?',
		cta: 'Su negocio tiene un desafío.\nEncontremos la dirección.',
		ctaText: 'Cuéntenos qué quiere transformar. El primer paso es una buena conversación.',
		ctaButton: 'Cuéntenos su desafío',
		footer: 'Claridad para decidir. Tecnología para evolucionar.',
		rights: 'Todos los derechos reservados.',
		back: 'Volver arriba',
		light: 'Activar modo claro',
		dark: 'Activar modo oscuro',
		menu: 'Abrir navegación',
		close: 'Cerrar',
		language: 'Idioma',
		skip: 'Ir al contenido',
		formTitle: 'Entendamos su desafío.',
		formDesc: 'Prepare un resumen de su proyecto para iniciar una conversación con Vértice.',
		name: 'Su nombre',
		company: 'Empresa',
		email: 'Correo profesional',
		challenge: '¿Qué quiere transformar?',
		submit: 'Preparar contacto',
		download: 'Descargar resumen',
		formNote: 'El contacto del equipo aún no está configurado. Puede descargar su resumen; no se enviará ningún dato.',
		ready: 'Resumen listo. Abra su correo o descargue una copia.',
		send: 'Abrir correo',
		error: 'No se pudo completar. Inténtelo de nuevo.',
		assistant: 'Asistente Vértice',
		assistantDesc: 'Explore nuestras soluciones',
		aiDemo: 'Guía de servicios · respuestas locales, sin IA conectada',
		aiLive: 'Asistente con IA · evite compartir datos sensibles',
		aiHello: '¡Hola! ¿Qué área quiere transformar? Elija un tema o describa su desafío.',
		aiPlaceholder: 'Cuéntenos su desafío…',
		aiSend: 'Enviar mensaje',
		aiBusy: 'Preparando respuesta…',
		aiFail: 'El asistente no está disponible. Inténtelo de nuevo o contacte al equipo.',
		aiDefault: 'Podemos ayudar con BI, datos, automatización, IA y aplicaciones. ¿Qué área se acerca a su desafío?',
		aiTopics: ['Visualizar datos financieros', 'Automatizar procesos', 'Explorar IA'],
		aiAnswers: ['Podemos organizar sus fuentes y crear dashboards de ingresos, gastos, márgenes e indicadores. Empezamos entendiendo las decisiones de su equipo.', 'Mapeamos tareas repetitivas, sistemas y puntos de aprobación. Después proponemos integraciones y automatizaciones adecuadas.', 'Evaluamos el caso de uso, los datos y los riesgos antes de proponer chatbots o agentes. La supervisión humana forma parte de la solución.'],
		solutionCTA: 'Conversar sobre esta solución',
	},
};
export type Language = keyof typeof content;
